name: ci

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: moonbitlang/setup-moonbit@v1
      - run: moon fmt --check
      - run: moon check --target js
      - run: moon test --target js
      - run: moon check --target wasm-gc
      - run: moon test --target wasm-gc
      - run: moon info
